python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=10
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=20
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=30
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=40
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=50
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=60
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=70
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=80
python3 attention.py --mode=ACMIL --weights-folder="attention2_resnet34_lr_decay" --histories-folder="attention2_resnet34_lr_decay" --learning-rate=0.0002 --weight-decay=0.00001 --epochs=10 --features=resnet34 --use-lr-decay=true --dropout=0 --last-epoch=90
